"""
Story Entities (Pydantic Schemas)
Request/Response models for stories domain.
"""
import uuid
from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class StoryStatus(str, Enum):
    """Story generation status."""
    PENDING = "pending"
    GENERATING_SCRIPT = "generating_script"
    GENERATING_ASSETS = "generating_assets"
    STITCHING = "stitching"
    COMPLETED = "completed"
    FAILED = "failed"


# ========================
# Scene Schemas
# ========================

class SceneCreate(BaseModel):
    """Schema for creating a scene."""
    order: int = Field(..., ge=0)
    narration: str = Field(..., min_length=1)
    visual_prompt: str = Field(..., min_length=1)
    duration_seconds: Optional[float] = Field(None, ge=1, le=30)


class SceneResponse(BaseModel):
    """Schema for scene response."""
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    story_id: uuid.UUID
    order: int
    narration: str
    visual_prompt: str
    audio_path: Optional[str] = None
    video_path: Optional[str] = None
    image_path: Optional[str] = None
    duration_seconds: Optional[float] = None
    created_at: datetime


class SceneUpdate(BaseModel):
    """Schema for updating a scene."""
    narration: Optional[str] = None
    visual_prompt: Optional[str] = None
    duration_seconds: Optional[float] = None


# ========================
# Story Schemas
# ========================

class StoryCreate(BaseModel):
    """Schema for creating a story manually."""
    project_id: uuid.UUID
    title: str = Field(..., min_length=1, max_length=500)
    prompt: str = Field(..., min_length=10)
    style_prefix: Optional[str] = Field(None, max_length=255)
    voice_id: Optional[str] = Field(None, max_length=100)


class StoryGenerateRequest(BaseModel):
    """Schema for generating a story with AI."""
    project_id: uuid.UUID
    prompt: str = Field(..., min_length=10, max_length=2000)
    style_prefix: Optional[str] = Field(None, max_length=255)
    voice_id: Optional[str] = Field(None, max_length=100)
    target_duration_seconds: int = Field(60, ge=15, le=180)
    num_scenes: int = Field(5, ge=2, le=15)


class StoryResponse(BaseModel):
    """Schema for story response."""
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    project_id: uuid.UUID
    title: str
    prompt: str
    script: Optional[str] = None
    status: str
    error_message: Optional[str] = None
    video_path: Optional[str] = None
    thumbnail_path: Optional[str] = None
    duration_seconds: Optional[int] = None
    style_prefix: Optional[str] = None
    voice_id: Optional[str] = None
    quality_score: Optional[float] = None
    created_at: datetime
    updated_at: datetime
    scene_count: int = 0


class StoryWithScenes(StoryResponse):
    """Story with scenes included."""
    scenes: list[SceneResponse] = []


class StoryUpdate(BaseModel):
    """Schema for updating a story."""
    title: Optional[str] = Field(None, max_length=500)
    script: Optional[str] = None
    style_prefix: Optional[str] = None
    voice_id: Optional[str] = None


class StoryListResponse(BaseModel):
    """Paginated story list."""
    items: list[StoryResponse]
    total: int
    page: int
    size: int


# ========================
# AI Generation Schemas
# ========================

class GeneratedScene(BaseModel):
    """Scene generated by Gemini."""
    scene_number: int
    narration: str
    visual_description: str
    duration_seconds: float


class GeneratedScript(BaseModel):
    """Complete script generated by Gemini."""
    title: str
    scenes: list[GeneratedScene]
    total_duration_seconds: float
